BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-products/images/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-ss-mgr"
BBFILE_PRIORITY_qti-ss-mgr = "12"
BBFILE_PATTERN_qti-ss-mgr := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_qti-ss-mgr = "rocko thud dunfell"
