#!/bin/sh /etc/rc.common

# Copyright (c) 2021-2022, 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

if [ -e "/etc/data/mbim_early_init" ]; then
    START=04
    STOP=95
else
    START=15
    STOP=84
fi

start() {
    echo start > /sys/class/remoteproc/remoteproc0/state
}

stop() {
    echo "Stopping modem service"
    echo stop > /sys/class/remoteproc/remoteproc0/state
}
