#!/bin/sh /etc/rc.common

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

if [ -e "/etc/data/mbim_early_init" ]; then
    START=04
    STOP=95
else
    START=15
    STOP=84
fi

start() {
    for i in 0 1; do
        NAME=$(cat /sys/class/remoteproc/remoteproc${i}/name)
        if [ "$NAME" = "4000000.remoteproc" ]; then
            echo "Modem found at remoteproc${i}"
            echo start > /sys/class/remoteproc/remoteproc${i}/state
        fi
    done

}

stop() {
    echo "Stopping modem service"
    for i in 0 1; do
        NAME=$(cat /sys/class/remoteproc/remoteproc${i}/name)
        if [ "$NAME" = "4000000.remoteproc" ]; then
            echo stop > /sys/class/remoteproc/remoteproc${i}/state
        fi
    done
}
